name: VeryHeight
version: ${project.version}
main: priv.inshin.veryheight.VeryHeight
api-version: '1.13'
authors: [InShin]
description: very height
commands:
  veryheight:
    usage: /<command> reconfig
    description: Reload config
    permission: inshin.veryheight.reconfig

permissions:
  inshin:
    veryheight:
      reconfig:
        default: op
        description: Reload config permissions
